# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb6d6e44324ef34807b3123a058801c8d79f8caaa09b82253772b8d870a0a34540567fb20bb46402892b89add29d17cafe5d6ebe68a904892a0e5838e4e73fbb

test:
  secret_key_base: 639cf18d828b7dce493ec0f8fe862e7418cff0bd0e7a256b98dd7d5d0f9eda0b7cee2c0dd324c196015bfff8777319b74b967329f21b827879c51a1e1f7d3a71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  #secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: thegeneratedtoken
